name: Deploy Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/grycccry13/my-docker-app:latest .
          echo "Image built successfully"

      - name: Login to GHCR
        uses: actions/github-script@v6
        with:
          script: |
            const token = context.github.token;
            const response = await github.rest.actions.createRegistrationTokenForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(response.data.token);
            core.setOutput('docker_token', response.data.token);

      - name: Authenticate with GHCR
        run: |
          echo "${{ steps.Login_to_GHCR.outputs.docker_token }}" | docker login ghcr.io -u $GITHUB_ACTOR -p -
          echo "Logged in to GHCR successfully"

      - name: Push the Docker image
        run: |
          docker push ghcr.io/grycccry13/my-docker-app:latest
          echo "Image pushed successfully"

      - name: Output Image URL
        run: |
          echo "::set-output name=image_url::ghcr.io/grycccry13/my-docker-app:latest"


